# Generated by Django 4.2.5 on 2023-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting_for_robot',
            field=models.BooleanField(default=False),
        ),
    ]
